importScripts('js/cache-polyfill.js');


self.addEventListener('install', function(e) {
 e.waitUntil(
   caches.open('imagineee').then(function(cache) {
     return cache.addAll([
      '',
      'api/cdn/font/ibmplex/mono/font.css',
      'api/cdn/font/ibmplex/mono/IBMPlexMono-Light.ttf',
      '404.html',
  'about.html',
  'js/cache-polyfill.js',
  'css',
  'favi.fab',
  'Favicon',
  'file-lister.js',
  'github.htm',
  'icon',
  'img',
  'index.html',
  'js',
  'LICENSE',
  'manifest.json',
  'new colour scheme.css',
  'o.md',
  'projects.html',
  'README.md',
  'sw.js',
  'template.html',
  'css/about.css',
  'css/global.css',
  'css/home.css',
  'css/projects.css',
  'Favicon/android-chrome-192x192.png',
  'Favicon/android-chrome-512x512.png',
  'Favicon/apple-icon-180.png',
  'Favicon/apple-splash-1125-2436.jpg',
  'Favicon/apple-splash-1136-640.jpg',
  'Favicon/apple-splash-1170-2532.jpg',
  'Favicon/apple-splash-1242-2208.jpg',
  'Favicon/apple-splash-1242-2688.jpg',
  'Favicon/apple-splash-1284-2778.jpg',
  'Favicon/apple-splash-1334-750.jpg',
  'Favicon/apple-splash-1536-2048.jpg',
  'Favicon/apple-splash-1620-2160.jpg',
  'Favicon/apple-splash-1668-2224.jpg',
  'Favicon/apple-splash-1668-2388.jpg',
  'Favicon/apple-splash-1792-828.jpg',
  'Favicon/apple-splash-2048-1536.jpg',
  'Favicon/apple-splash-2048-2732.jpg',
  'Favicon/apple-splash-2160-1620.jpg',
  'Favicon/apple-splash-2208-1242.jpg',
  'Favicon/apple-splash-2224-1668.jpg',
  'Favicon/apple-splash-2388-1668.jpg',
  'Favicon/apple-splash-2436-1125.jpg',
  'Favicon/apple-splash-2532-1170.jpg',
  'Favicon/apple-splash-2688-1242.jpg',
  'Favicon/apple-splash-2732-2048.jpg',
  'Favicon/apple-splash-2778-1284.jpg',
  'Favicon/apple-splash-640-1136.jpg',
  'Favicon/apple-splash-750-1334.jpg',
  'Favicon/apple-splash-828-1792.jpg',
  'Favicon/apple-touch-icon.png',
  'Favicon/favicon-16x16.png',
  'Favicon/favicon-32x32.png',
  'Favicon/favicon.ico',
  'Favicon/favicon_io (1).zip',
  'Favicon/favicon_io.zip',
  'Favicon/manifest-icon-192.png',
  'Favicon/manifest-icon-512.png',
  'Favicon/maskable_icon.png',
  'Favicon/site.webmanifest',
  'icon/codepen.png',
  'icon/Github.png',
  'icon/imagineee back.svg',
  'icon/medium.webp',
  'icon/open.png',
  'icon/so.png',
  'icon/user.png',
  'img/back.gif',
  'img/background.png',
  'img/charcoal.jpg',
  'img/galaxy.jpg',
  'img/head_wall.png',
  'img/logo',
  'img/mt.jpg',
  'img/stars.jpg',
  'img/waterdrops.jpg',
  'img/watery back.png',
  'img/wave.svg',
  'img/wooddunes.jpg',
  'img/logo/banner.png',
  'img/logo/imagineee logo min size.png',
  'img/logo/imagineee logo nano size.png',
  'img/logo/imagineee logo pixelated.png',
  'img/logo/imagineee-favicon.png',
  'img/logo/long banner min size.png',
  'js/global.js',
  'js/home.js',
  'js/projects.js',
  'js/vanilla-tilt.min.js'
     ]);
   })
 );
});

if (navigator.onLine == true) {
  caches.open('imagineee').then(function(cache) {
    return cache.addAll([
      '',
      '404.html',
  'about.html',
  'js/cache-polyfill.js',
  'css',
  'favi.fab',
  'Favicon',
  'file-lister.js',
  'github.htm',
  'icon',
  'img',
  'index.html',
  'js',
  'LICENSE',
  'manifest.json',
  'new colour scheme.css',
  'o.md',
  'projects.html',
  'README.md',
  'sw.js',
  'template.html',
  'css/about.css',
  'css/global.css',
  'css/home.css',
  'css/projects.css',
  'Favicon/android-chrome-192x192.png',
  'Favicon/android-chrome-512x512.png',
  'Favicon/apple-icon-180.png',
  'Favicon/apple-splash-1125-2436.jpg',
  'Favicon/apple-splash-1136-640.jpg',
  'Favicon/apple-splash-1170-2532.jpg',
  'Favicon/apple-splash-1242-2208.jpg',
  'Favicon/apple-splash-1242-2688.jpg',
  'Favicon/apple-splash-1284-2778.jpg',
  'Favicon/apple-splash-1334-750.jpg',
  'Favicon/apple-splash-1536-2048.jpg',
  'Favicon/apple-splash-1620-2160.jpg',
  'Favicon/apple-splash-1668-2224.jpg',
  'Favicon/apple-splash-1668-2388.jpg',
  'Favicon/apple-splash-1792-828.jpg',
  'Favicon/apple-splash-2048-1536.jpg',
  'Favicon/apple-splash-2048-2732.jpg',
  'Favicon/apple-splash-2160-1620.jpg',
  'Favicon/apple-splash-2208-1242.jpg',
  'Favicon/apple-splash-2224-1668.jpg',
  'Favicon/apple-splash-2388-1668.jpg',
  'Favicon/apple-splash-2436-1125.jpg',
  'Favicon/apple-splash-2532-1170.jpg',
  'Favicon/apple-splash-2688-1242.jpg',
  'Favicon/apple-splash-2732-2048.jpg',
  'Favicon/apple-splash-2778-1284.jpg',
  'Favicon/apple-splash-640-1136.jpg',
  'Favicon/apple-splash-750-1334.jpg',
  'Favicon/apple-splash-828-1792.jpg',
  'Favicon/apple-touch-icon.png',
  'Favicon/favicon-16x16.png',
  'Favicon/favicon-32x32.png',
  'Favicon/favicon.ico',
  'Favicon/favicon_io (1).zip',
  'Favicon/favicon_io.zip',
  'Favicon/manifest-icon-192.png',
  'Favicon/manifest-icon-512.png',
  'Favicon/maskable_icon.png',
  'Favicon/site.webmanifest',
  'icon/codepen.png',
  'icon/Github.png',
  'icon/imagineee back.svg',
  'icon/medium.webp',
  'icon/open.png',
  'icon/so.png',
  'icon/user.png',
  'img/back.gif',
  'img/background.png',
  'img/charcoal.jpg',
  'img/galaxy.jpg',
  'img/head_wall.png',
  'img/logo',
  'img/mt.jpg',
  'img/stars.jpg',
  'img/waterdrops.jpg',
  'img/watery back.png',
  'img/wave.svg',
  'img/wooddunes.jpg',
  'img/logo/banner.png',
  'img/logo/imagineee logo min size.png',
  'img/logo/imagineee logo nano size.png',
  'img/logo/imagineee logo pixelated.png',
  'img/logo/imagineee-favicon.png',
  'img/logo/long banner min size.png',
  'js/global.js',
  'js/home.js',
  'js/projects.js',
  'js/vanilla-tilt.min.js'
    ]);
  })
}

self.addEventListener('fetch', function(event) {
    console.log(event.request.url);
    event.respondWith(
        caches.match(event.request).then(function(response) {
            return response || fetch(event.request);
        })
        );
    });
